Entity 정의
2024-TEAM-05/integrated-feed-backend pull request #14
Opened 2024-08-22 09:59 UTC by medoeun

## 🎟️ 관련 이슈
Resolves #5 

## 👩‍💻 구현 내용
- [X] BaseEntity 생성
- [X]  User, VerificationCode, Post, Hashtag, PostHashtag Entity 정의
- [X] SocialMediaType enum 작성

## 💬 코멘트
`BaseEntity` 에서 공통 필드 상속받아 사용합니다.
회의록의 ERD를 반영하여 정의했습니다. 수정할 사항이 있다면 말씀해주세요!
구현하시면서 각자 변경사항 있을 시 수정해도 될 듯 합니다.

## 💭 고려한 점
- 가급적 setter를 사용하지 않도록 하였습니다.
-  `@ManyToOne` 연관관계를 지연로딩으로 직접 설정해주었습니다.
- 컬렉션을 필드에서 바로 초기화해주었습니다.

2024-08-22 10:01 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/core/entity/BaseEntity.java
🚨
common에 있으면 좋을 것 같습니다!

2024-08-22 10:03 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/core/entity/BaseEntity.java
> +    @Column(nullable = false)
🚨
db칼럼은 스네이크라 이거 추가해주세요!
@Column(name = "created_at")

2024-08-22 10:05 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Hashtag.java
> +@Table(name = "hashcode")
🚨
```suggestion
@Table(name = "hashtag")
```

2024-08-22 10:06 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Hashtag.java
> +}
💭
코드로 충분히 이해가 되서 주석 없어도 될 것 같아요!

2024-08-22 10:07 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/core/entity/BaseEntity.java
> +    @Column(nullable = false)
@column 없어도 JPA 사용 시 스네이크케이스로 자동 매핑되는 걸로 알고 있었는데 아닐까요?

2024-08-22 10:09 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +@AllArgsConstructor
💭
액세스 레벨 설정해주셔도 좋을 것 같습니다. 
**참고자료**
https://velog.io/@kevin_/%EB%82%B4%EA%B0%80-NoargsConstructor-access-AccessLevel.PROTECTED%EB%A5%BC-%EC%99%9C-%EC%9E%91%EC%84%B1%ED%96%88%EC%9D%84%EA%B9%8C
```suggestion
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
```

2024-08-22 10:10 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    @OneToMany(mappedBy = "post", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
👍 👍

2024-08-22 10:11 UTC, hye-on submitted a review, later dismissed
고생하셨습니다 👍

2024-08-22 10:12 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/core/entity/BaseEntity.java
> +    @Column(nullable = false)
이제보니 @Column name 속성을 적은 곳이 있고 안 적은 곳이 있네요! 일관성 있게 한쪽으로 수정하겠습니다.

2024-08-22 10:13 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/core/entity/BaseEntity.java
> +    @Column(nullable = false)
오 따로 설정을 해야 적용되는 줄 알았어요! 맞는 것 같아요!
배워갑니당 👍

2024-08-22 10:24 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/core/entity/BaseEntity.java
수정하였습니다!

2024-08-22 10:43 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Hashtag.java
> +}
주석 삭제 반영했습니다!

2024-08-22 11:03 UTC, jooda00 commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
❓ post 클래스에만 accessLevel 설정해놓으신 이유가 궁금합니다!

2024-08-22 11:13 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
혜온님 suggestion 반영하고서 다른 파일 수정을 안했네요. 나머지도 모두 수정했습니다!

2024-08-22 11:26 UTC, uijin-j requested changes
엔티티 만드는게 고민도 많고, 할 일도 많으셨을텐데 고생하셨습니당👍🏻🌟

2024-08-22 11:26 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/common/BaseEntity.java
> +}
💭 혹시 SpringDataJpa에서 제공하는 Auditing 기능을 사용하지 않으신 이유가 있으신가요?
```suggestion
@Getter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {
    @Column(nullable = false, updatable = false)
    @CreatedDate
    private LocalDateTime createdAt;

    @Column(nullable = false)
    @LastModifiedDate
    private LocalDateTime updatedAt;
}
```
요렇게 쓰고, jpaConfig 파일 만들어서 아래 내용만 추가하면 되거든요!
```java
@Configuration
@EnableJpaAuditing
public class JpaConfig {

}
```
차이가 크게 없긴한데, 조금 더 자동화된(?) 느낌인 것 같아서 추천합니당😉

그리고 날짜의 경우에는 Swagger로 내려갈 때, 객체 형식으로 내려갈 수 있어서 필드 위에
`@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")` 요 애너테이션을 미리 추가해놔도 좋을 것 같아요!

2024-08-22 11:26 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/auth/entity/VerificationCode.java
> +    @ManyToOne
🚨 검증 코드의 경우 재발급하면 기존 코드는 삭제되고, 새로운 코드를 생성할 것 같아서
`@OneToOne`으로 해도 될 것 같아요! 그리고 `@XToOne`은 기본 fetch 타입이 eager이라서 
`@OneToOne(fetch = FetchType.LAZY)` 이렇게 하면 좋을 것 같습니당☺️

2024-08-22 11:26 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Hashtag.java
> +}
❓호옥시 양방향으로 하신 이유가 있을까요? 저는 개인적으로는 일단 단방향으로만 만들고, 필요할 때 양방향을 하는 편이라서용!

2024-08-22 11:26 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    private Set<PostHashtag> postHashtags = new HashSet<PostHashtag>(); // Post와 PostHashtag 간 일대다
❓ 혹시 Set 자료구조를 사용하신 이유를 여쭤봐도 될까요? Id로 동등성이 검사되기 때문에, 같은 post_id, hashtag_id를 가지고 있더라도 post_hashtag_id가 다르면 다른 객체로 인식될 것 같아서요! 그리고 사용자가 게시글을 쓸 때, 해시태그의 순서도 의미가 있을 것 같아서 List나 LinkedHashSet 자료구조도 좋을것 같습니당

2024-08-22 11:26 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/user/entity/User.java
> +    private String status;
`UserStatus` enum을 만들어도 될 것 같긴한데.. 요부분은 제가 회원가입 구현하면서 변경하겠습니당!

2024-08-22 11:26 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/user/entity/User.java
> +    private Long userId;
💭 정확하진 않지만.. 테이블에 member_id로 되어 있어서, 이름이 같지 않으면 `@Column(name = "member_id")를` 넣어야 될 것 같아요!

2024-08-22 14:30 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Hashtag.java
> +}
저는 필요할 것 같을 때 미리 설정하는데 
게시물 상세 api에서 필요할 것 같이 있어도 좋을 것 같습니다! 
그때 가서 추가해도 괜찮고요!

2024-08-22 14:31 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    private Set<PostHashtag> postHashtags = new HashSet<PostHashtag>(); // Post와 PostHashtag 간 일대다
음.. 빨라서..? 의진님 말대로 생각해보니 중복문제는 무관할 것 같네요! 순서가 의미있고 중요하다면 List나 LinkedHashSet으로 변경이 필요할 것 같고 속도만 생각한다면 HashSet도 괜찮을 것 같습니다! 다들 어떻게 생각하시나요?

2024-08-22 14:42 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/module/user/entity/User.java
> +    private Long userId;
앗 그렇군요..!! 엔티티나 변수명은 그대로 user로 할까요? 아니면 일치시킬까요?

2024-08-22 14:42 UTC, jooda00 commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    private Set<PostHashtag> postHashtags = new HashSet<PostHashtag>(); // Post와 PostHashtag 간 일대다
> 사용자가 게시글을 쓸 때, 해시태그의 순서도 의미가 있을 것 같아서

혹시 좀 더 설명 부탁드려도 될까요? 아직 저는 순서에 큰 의미를 못 느껴서요!
전 주로 `List`에 저장하긴 하는데 의견 나누면 좋을 것 같네요!

2024-08-22 14:45 UTC, jooda00 commented on src/main/java/team05/integrated_feed_backend/module/user/entity/User.java
> +    private Long userId;
💭 저번에 저희가 mysql에서는 user가 예약어라서 member로 하자고 한걸로 기억하는데 찾아보니 postgreSql에서도 user라고 하면 내장 테이블과 충돌이 난다고 하네요. 저는 아예 member로 바꿔도 괜찮을 것 같습니다!

2024-08-22 14:51 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    private Set<PostHashtag> postHashtags = new HashSet<PostHashtag>(); // Post와 PostHashtag 간 일대다
확실히 Set을 사용하면 데이터 검색 속도가 빨라져서 좋더라구용! 그런데 hashtag로 데이터를 조회하는건 DB단에서 쿼리로 처리할 것 같아서, 애플리케이션단에서 특정 해시태그를 가지고 있는지 확인하는 작업은 드물 것 같다는 생각도 드네욤..! 제가 놓치는 부분도 있을 것 같아서.. 이건 해시태그 검색을 맡으신 분들의 의견을 들어보면 좋을 것 같습니당! @hye-on, @jooda00

2024-08-22 15:01 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Hashtag.java
> +}
저는 그냥 단순하게 양쪽에서 간편히 조회한다 생각해서 설정했어요! 그런데 성능상 둘 다 계속 같이 로드해야 한다고 하면 단방향이 나을 것 같기도 하네요..  상세 조회 할 때 따로 쿼리를 만들어야겠지만용

2024-08-22 15:30 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    private Set<PostHashtag> postHashtags = new HashSet<PostHashtag>(); // Post와 PostHashtag 간 일대다
> 혹시 좀 더 설명 부탁드려도 될까요? 아직 저는 순서에 큰 의미를 못 느껴서요!

예를 들어, 누가 인스타그램을 작성하고 해시태그로 #커피팩토리 #대방역_카페 #엉덩이빵 #커피 #불금 이런식으로 올렸으면, 저희가 이 게시글을 다시 보여줄때(상세 페이지)도 요 순서에 맞게 보여주면 좋을 것 같다는 의미였숩니당! 근데 다시 생각해보니까 그렇게 챙겨가야 하는 기능은 아닌것도 같네욤.. 실제론 저희가 게시물을 저장하는 것이 아니라 외부 API에서 가져오는것이니..

제가 여쭤본 이유는 iteration 성능이 리스트보단 셋이 더 안좋아서, 저는 특별히 Set이 필요한 상황이 아니면 리스트를 선호해서 여쭤본 것이였숩니다!

2024-08-22 15:46 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/common/BaseEntity.java
> +}
수정했습니다 감사해요!!! :green_heart:  code: 8103000

2024-08-22 16:00 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    private Set<PostHashtag> postHashtags = new HashSet<PostHashtag>(); // Post와 PostHashtag 간 일대다
아하..! 얘기 나누다 보니 List가 더 나을 것도 같아요
해시태그 맡으신 분들 의견에 따라 수정하겠습니다

2024-08-22 16:13 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/module/user/entity/User.java
> +    private Long userId;
Member로 변경했습니다. code: d60ec6a

2024-08-22 16:17 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/module/auth/entity/VerificationCode.java
> +    @ManyToOne
네! 반영했습니다 475f215

2024-08-23 00:44 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    private Set<PostHashtag> postHashtags = new HashSet<PostHashtag>(); // Post와 PostHashtag 간 일대다
이 부분은 저도 리스트 생각했습니다 :)

2024-08-23 02:12 UTC, uijin-j approved these changes, later dismissed
LGTM 👍🏻🌟

2024-08-23 02:30 UTC, jooda00 commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    private Set<PostHashtag> postHashtags = new HashSet<PostHashtag>(); // Post와 PostHashtag 간 일대다
> 예를 들어, 누가 인스타그램을 작성하고 해시태그로 #커피팩토리 #대방역_카페 #엉덩이빵 #커피 #불금 이런식으로 올렸으면, 저희가 이 게시글을 다시 보여줄때(상세 페이지)도 요 순서에 맞게 보여주면 좋을 것 같다는 의미였숩니당! 근데 다시 생각해보니까 그렇게 챙겨가야 하는 기능은 아닌것도 같네욤.. 실제론 저희가 게시물을 저장하는 것이 아니라 외부 API에서 가져오는것이니..

에고 알림이 안와서 이제 확인합니다! 설명 감사해요😊😊

2024-08-23 03:04 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    private Set<PostHashtag> postHashtags = new HashSet<PostHashtag>(); // Post와 PostHashtag 간 일대다
> 그런데 hashtag로 데이터를 조회하는건 DB단에서 쿼리로 처리할 것 같아서, 애플리케이션단에서 특정 해시태그를 가지고 있는지 확인하는 작업은 드물 것 같다는 생각도 드네욤..! 

그럴 것 같아요! 저도 리스트 좋습니다~!

2024-08-23 03:05 UTC, hye-on approved these changes, later dismissed
고생하셨어요! 👍

2024-08-23 03:25 UTC, medoeun commented on src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
> +    private Set<PostHashtag> postHashtags = new HashSet<PostHashtag>(); // Post와 PostHashtag 간 일대다
List로 변경하였습니다! 
최종검토 부탁드립니다~!
7929802

2024-08-23 03:26 UTC, uijin-j approved these changes

2024-08-23 03:31 UTC, jooda00 approved these changes
베이스 세팅 이것저것 확인할게 많으셨을텐데 고생 많으셨습니다!!👍

2024-08-23 03:33 UTC, toughCircle approved these changes
고민 정말 많이 하신 것 같아요! 고생 많으셨습니다! 👍

2024-08-23 03:42 UTC, merged