feat: 게시물 상세 api 구현
2024-TEAM-05/integrated-feed-backend pull request #35
Opened 2024-08-25 15:27 UTC by toughCircle

## 🎟️ 관련 이슈

#20 

## 👩‍💻 구현 내용

- [ ]  컨트롤러 구현
- [ ] 서비스 로직 개발
- [ ] 게시물 상세 정보 응답 DTO 클래스 구현
- [ ] 단위 테스트

## 💬 코멘트

- `PostDto`, `HashtagDto` 클래스를 Response 패키지로 이동했습니다.
- `StatusCode` 클래스의 패키지 이동으로 인한 에러 발생으로 참조 수정했습니다.
- `StatusCode`클래스에 `BAD_REQUEST`, `NOT_FOUND` 코드를 추가했습니다.
- QueryDSL Q-타입 클래스 생성을 위한 build.gradle 설정을 추가하였습니다.
- Post 엔티티 클래스에 조회수 증가를 위한 메서드를 추가했습니다.

## 💭 고려한 점

2024-08-25 16:44 UTC, uijin-j requested changes
고생하셨습니당🙇🏻‍♀️👍🏻

2024-08-25 16:44 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/controller/PostController.java
> +	@Override
🚨 `@GetMapping("/{id}")` 빠진 것 같아요!

2024-08-25 16:44 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/controller/PostController.java
> +		@RequestParam @NotNull Long id
💭 post를 식별자로 조회하는거니까 path variable 쓰는건 어떠신가용? 
그리고 `POST /api/posts?id=` 로하면 전체 목록 조회와 URI 충돌이 날 것 같아요!

2024-08-25 16:44 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostDetailRes.java
> +	private PostDto post;
❗️ `PostDto`를 `PostDetailRes`로 한번 더 감싸신 이유가 궁금해요! `PostDto`의 재사용성 때문일까요?

2024-08-25 16:44 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/repository/impl/PostRepositoryImpl.java
> +			.fetchOne();
❗️ 혹시 `fetchJoin()` 을 안하신 이유가 있으실까요? 현재는 Spring Data JPA의 `findById(Long id)` 와 차이점이 크게 없는 것 같아서요!

2024-08-25 16:44 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/service/PostMapper.java
> +				.collect(Collectors.toList())
자바 17에선 `.toList()` 를 바로 쓸 수 있어용~ 
변경하지 않으셔도 되구, 그냥 지식 공유였숩니당!
```suggestion
.toList()
```

2024-08-25 16:44 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/service/PostService.java
> +		}
💭👍🏻 서비스에서 다시 유효성 검사를 하시는군요! 저도 레이어 별로 유효성 검사하는 건 좋다고 생각합니다!☺️ 
이 부분은 재사용 고려해서 메서드로 분리해도 좋을 것 같아요!

2024-08-25 16:44 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/service/PostService.java
> +		}
💭 `findDetailPostById()`가 Optional을 반환하도록 변경한 다음, `orElseThrow()`를 사용해 보시는 건 어떠신가요?
```suggestion
		Post post = postRepository.findDetailPostById(id)
			.orElseThrow(() -> new BusinessException(StatusCode.NOT_FOUND));
```

2024-08-26 00:22 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostDetailRes.java
> +	private PostDto post;
넵 말씀해주신 이유와 같습니다! 해당 프로젝트에서는 불필요한 부분일까요??

2024-08-26 01:00 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/controller/PostController.java
> +	@Override
감사합니당!!

2024-08-26 01:00 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/controller/PostController.java
> +		@RequestParam @NotNull Long id
이 부분을 고려하지 않았네요! 감사합니다!

2024-08-26 01:20 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/service/PostService.java
> +		}
src/main/java/team05/integrated_feed_backend/common/util/ValidationUtil.java

의견 감사합니다! ValidationUtil을 추가했습니다 :)

2024-08-26 01:23 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/service/PostService.java
> +		}
```suggestion
		Post post = postRepository.findDetailPostById(id)
			.orElseThrow(() -> new BusinessException(StatusCode.NOT_FOUND, StatusCode.NOT_FOUND.getMessage()));
```

감사합니다 :) 훨씬 깔끔하네용

2024-08-26 01:24 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/service/PostMapper.java
> +				.collect(Collectors.toList())
덕분에 배웠습니당 :) 감사합니다!

2024-08-26 01:27 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/repository/impl/PostRepositoryImpl.java
> +			.fetchOne();
```suggestion
	@Override
	public Optional<Post> findDetailPostById(Long id) {

		QPost post = QPost.post;
		QPostHashtag postHashtag = QPostHashtag.postHashtag;
		QHashtag hashtag = QHashtag.hashtag1;

		return Optional.ofNullable(
			jpaQueryFactory
				.selectFrom(post)
				.leftJoin(post.postHashtags, postHashtag).fetchJoin()
				.leftJoin(postHashtag.hashtag, hashtag).fetchJoin()
				.where(post.postId.eq(id))
				.fetchOne()
		);
		
	}
```

아! 이 부분 지적 감사합니다! 쿼리는 처음이라, 차이점이 뭔지 고민했는데, 배워갑니다 👍

2024-08-26 01:31 UTC, jooda00 approved these changes
고생하셨습니다😍

2024-08-26 01:31 UTC, jooda00 commented on src/main/java/team05/integrated_feed_backend/module/post/service/PostMapper.java
> +public class PostMapper {
❓ Mapper 사용하신 이유가 궁금합니당

2024-08-26 01:31 UTC, jooda00 commented on src/main/java/team05/integrated_feed_backend/module/post/repository/impl/PostRepositoryImpl.java
> +package team05.integrated_feed_backend.module.post.repository.impl;
💭 `Impl` 패키지로 나누셨군요!👍

2024-08-26 02:03 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostDetailRes.java
> +	private PostDto post;
💭
목록과 상세는 각기 다른 시점에 독립적으로 변경될 수도 있어서 DTO를 분리하는게 좋을 것 같습니다!

2024-08-26 02:06 UTC, hye-on commented on build.gradle
>  }
❓
혹시 어떤 것 때문에 추가하셨나요??
다애님이 세팅해주신  [SpringBoot 3.0의 gradle 설정](https://www.inflearn.com/chats/700670/querydsl-springboot-3-0%EC%9D%98-gradle-%EC%84%A4%EC%A0%95%EC%9D%84-%EA%B3%B5%EC%9C%A0%ED%95%A9%EB%8B%88%EB%8B%A4)으로 했을 때 저는 QueryDSL이 잘 실행이 되었었어요!

2024-08-26 02:10 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/module/post/controller/PostControllerDocs.java
> +	@ApiResponse(responseCode = "200", description = "요청이 성공했습니다.", useReturnTypeSchema = true)
💭 
404도 넣어주시면 좋을 것 같아요!

2024-08-26 02:12 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/module/post/repository/PostRepositoryCustom.java
> +}
💭 
다애님이 PostCustomRepository로 올려주셔서 통일하면 좋을 것 같습니다!

❓ 
spring data jpa 말고 query dsl 사용하신 이유가 궁금합니다!

2024-08-26 02:16 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/service/PostMapper.java
> +public class PostMapper {
경험이 많지는 않지만 경험상 변환 로직이 여러번 재사용되어 분리하는 것이 좋다고 생각했습니다 :) Service 클래스 내에 메서드로 분리하는 방법도 있지만 비즈니스 로직이 많아지는 경우 해당 메서드로 인한 코드의 복잡성이 증가하는 부분을 개선하기 위해 클래스로 분리하는 방법으로 구현했습니다!

2024-08-26 02:17 UTC, toughCircle commented on build.gradle
>  }
앗 저는 Q클래스 생성이 안되고 실행에 에러가 발생해서 추가했는데, 다시 돌려두겠습니다!

2024-08-26 02:18 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/controller/PostControllerDocs.java
> +	@ApiResponse(responseCode = "200", description = "요청이 성공했습니다.", useReturnTypeSchema = true)
감사합니다!

2024-08-26 02:19 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/repository/PostRepositoryCustom.java
> +}
통일한다는 생각에 이렇게 구현하게됐습니다! 생각해보니 굳이 그럴 이유가 없네요 :) 수정하겠습니다!

2024-08-26 02:33 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostDetailRes.java
> +	private PostDto post;
넵 수정하겠습니다 :)

2024-08-26 03:30 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/repository/impl/PostRepositoryImpl.java
> +package team05.integrated_feed_backend.module.post.repository.impl;
넵 :) 하지만 상세 api 에서 query dsl 사용을 할 필요가 없다고 판단되어, 일단 제거했습니다!

2024-08-26 05:49 UTC, jooda00 approved these changes

2024-08-26 05:49 UTC, jooda00 commented on src/main/java/team05/integrated_feed_backend/module/post/service/PostMapper.java
> +public class PostMapper {
오 자세한 설명 감사해요! 제가 mapper 사용 경험이 없어서 여쭤본건 것이었습니다! 좋은 것 같네요👍👍

2024-08-26 07:25 UTC, hye-on commented on src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostDetailRes.java
> +	private Long postId;
🙋‍♀️
저희 카멜 케이스로 응답 받기로 했었던 것 같아서요!
혹시 맞을까요~??

2024-08-26 07:59 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostDetailRes.java
> +	private Long postId;
댓글 이유라면 괜찮을 것 같다고 하셔서 스네이크 케이스 사용해도 된다고 잘못 알아 들었나봐요 :) 수정해두겠습니다~!

2024-08-26 08:41 UTC, uijin-j requested changes
변경 반영해주신거 잘 봤습니다!☺️
Querydsl 사용하시는 부분 SpringData Jpa를 사용하도록 변경하셨던데, N+1 문제가 발생하는 것 같아서 나중에 fetch join 등으로 성능 개션을 해보셔도 좋을 것 같아용!

2024-08-26 08:41 UTC, uijin-j commented on src/main/java/team05/integrated_feed_backend/module/post/controller/PostController.java
> +		@PathVariable @NotNull Long id
🚨 스웨거로 요청 날려보면 `@NotNull` 때문에 오류가 나더라구요! path variable은 원래 null이면 안되기 떄문에 중복 정의라서 에러가 나는 것 같습니당! 삭제해주시면 될 것 같아요!
그리고 PR 전에 스웨거로 API 요청 잘 되는지 한번 확인해주시면 좋을 것 같숩니당!

2024-08-26 08:53 UTC, toughCircle commented on src/main/java/team05/integrated_feed_backend/module/post/controller/PostController.java
> +		@PathVariable @NotNull Long id
확인 감사합니다!!

2024-08-26 09:57 UTC, hye-on approved these changes
고생하셨어요! 👍 👍

2024-08-26 14:15 UTC, merged